package Verein;


/**
* Verein/Vereinsmitglied.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vmitglied.idl
* Donnerstag, 7. Juni 2018 14:43 Uhr MESZ
*/

public interface Vereinsmitglied extends VereinsmitgliedOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Vereinsmitglied
